"""Broader, balanced performance matrix for the rebar experiment."""

MODULES = ["re", "candidates.ast_candidate", "candidates.vm_candidate", "candidates.rust_candidate"]
TRIALS = 13
WARMUPS = 4
ORDER_SEED = 1979121403
BOOTSTRAP_SEED = 1979121404
BOOTSTRAPS = 5000
CASES_PER_COHORT = 72


def C(case_id, cohort, category, api, lifecycle, pattern, string, ops, **values):
    return {"id": case_id, "cohort": cohort, "category": category, "api": api, "lifecycle": lifecycle, "pattern": pattern, "string": string, "ops": ops, "weight": 1, "flags": values.pop("flags", []), **values}


CASES = [
    C("cal.search.literal.hit", "calibration", "search-hit", "search", "compiled", "needle", "prefix needle suffix", 320),
    C("cal.search.literal.miss", "calibration", "search-miss", "search", "compiled", "absent", "ordinary text without the token", 320),
    C("cal.search.long-boundary", "calibration", "search-boundary", "search", "compiled", "END$", "x" * 4096 + "END", 48),
    C("cal.search.class-anchor", "calibration", "search-class", "search", "compiled", r"^item-[0-9]{3}$", "skip\nitem-204\nitem-x", 224, flags=["M"]),
    C("cal.match.prefix", "calibration", "match", "match", "compiled", r"[A-Z]{2}[0-9]{4}", "AB2048 trailing", 256),
    C("cal.fullmatch.structured", "calibration", "fullmatch", "fullmatch", "compiled", r"[a-z]+(?:_[a-z]+)*", "alpha_beta_gamma", 224),
    C("cal.search.look-capture", "calibration", "capture-look", "search", "compiled", r"(?<=id=)(?P<id>[0-9]+)(?=;)", "name=a;id=48291;ok=yes", 192),
    C("cal.findall.tokens", "calibration", "findall", "findall", "compiled", r"[A-Za-z_][A-Za-z0-9_]*", "alpha=one beta_2=two gamma3=three delta=four", 144),
    C("cal.finditer.groups", "calibration", "finditer", "finditer", "compiled", r"(?P<key>[a-z]+)=(?P<value>[0-9]+)", "a=1 bb=22 ccc=333 dddd=4444", 120),
    C("cal.split.capture", "calibration", "split", "split", "compiled", r"([,:])", "a,b:c,d:e,f:g,h", 160),
    C("cal.sub.template", "calibration", "sub", "sub", "compiled", r"(?P<word>[a-z]+)-(?P<num>[0-9]+)", "ab-12 cd-3 ef-456", 144, repl=r"\g<num>:\g<word>"),
    C("cal.subn.callable", "calibration", "subn-callable", "subn", "compiled", r"[a-z]+", "alpha 12 beta 34 gamma", 128, repl={"callable": "upper_bracket"}, count=2),
    C("cal.bytes.tokens", "calibration", "bytes", "findall", "compiled", rb"[A-Za-z_][A-Za-z0-9_]*", b"alpha=1 beta_2=2 \xff gamma=3", 128),
    C("cal.unicode.words", "calibration", "unicode", "findall", "compiled", r"\b\w+\b", "Aé_٣ 雪 and İıſK", 128),
    C("cal.cold.compile-search", "calibration", "cold", "search", "cold", r"(?P<name>[A-Za-z]+)-[0-9]{2,4}", "prefix widget-2048 suffix", 40),
    C("cal.module.warm", "calibration", "module", "search", "module", r"[a-z]+-[0-9]+", "prefix alpha-2048 suffix", 256),
    C("cal.empty.finditer", "calibration", "empty", "finditer", "compiled", r"\B|(?=,)", "ab,cd ef", 96),
    C("cal.backref.fullmatch", "calibration", "backref", "fullmatch", "compiled", r"([a-z]{2,4})-\1", "echo-echo", 128),
    C("cal.conditional.match", "calibration", "conditional", "match", "compiled", r"(<)?[A-Za-z]+(?(1)>|!)", "<alpha> trailing", 128),
    C("cal.atomic.search", "calibration", "branch-control", "search", "compiled", r"(?>ab|a)b+", "xx abbbbb yy", 128),
    C("cal.byteslike.findall", "calibration", "bytes-like", "findall", "compiled", rb"[A-Z]+|[0-9]+", b"AA12 BB345 CC7", 112, subject_kind="bytearray"),
    C("cal.unicode-name.search", "calibration", "unicode-name", "search", "compiled", r"\N{SNOWMAN}+", "text ☃☃☃ end", 128),
    C("cal.ignorecase.findall", "calibration", "ignore-case", "findall", "compiled", r"[a-z]+", "Alpha BETA gamma Delta", 128, flags=["I"]),
    C("cal.many.split", "calibration", "many-results", "split", "compiled", r"[,;]", "a,b;c,d;e,f;g,h;i,j;k,l", 112),
    C("cal.escape.text", "calibration", "escape", "escape", "module", "a+b [x] # tag\\tail", None, 224),
    C("cal.compile.only", "calibration", "compile", "compile", "cold", r"(?P<word>[A-Za-z_]+)(?:-[0-9]{1,4})?", None, 32),
    C("cal.scanner.search", "calibration", "scanner", "scanner", "compiled", r"(?P<word>[a-z]+)=[0-9]+", "a=1 bb=22 ccc=333 dddd=4444", 96),
    C("cal.match.surface", "calibration", "match-surface", "match-surface", "compiled", r"(?P<word>[A-Za-z]+)-(?P<num>[0-9]+)", "prefix alpha-2048 suffix", 144, expand=r"\g<num>:\g<word>"),

    C("hold.search.literal.hit", "holdout", "search-hit", "search", "compiled", "marker", "before marker after", 320),
    C("hold.search.literal.miss", "holdout", "search-miss", "search", "compiled", "missing", "all the usual words are present", 320),
    C("hold.search.long-boundary", "holdout", "search-boundary", "search", "compiled", "DONE$", "q" * 6144 + "DONE", 40),
    C("hold.search.class-anchor", "holdout", "search-class", "search", "compiled", r"^row_[A-F0-9]{4}$", "ignore\nrow_B17F\nrow_zzzz", 224, flags=["M"]),
    C("hold.match.prefix", "holdout", "match", "match", "compiled", r"[a-z]{3}[0-9]{2}", "abc42 remains", 256),
    C("hold.fullmatch.structured", "holdout", "fullmatch", "fullmatch", "compiled", r"(?:[A-Z][a-z]+)(?:-[A-Z][a-z]+)*", "North-East-West", 224),
    C("hold.search.look-capture", "holdout", "capture-look", "search", "compiled", r"(?<=code:)(?P<code>[A-Z]{2}[0-9]+)(?=,)", "x,code:ZX9021,next", 192),
    C("hold.findall.tokens", "holdout", "findall", "findall", "compiled", r"[a-z]+(?:_[0-9]+)?", "red_1 blue green_22 yellow black_333", 144),
    C("hold.finditer.groups", "holdout", "finditer", "finditer", "compiled", r"(?P<word>[a-z]+):(?P<num>[0-9]+)", "one:1 two:22 three:333 four:4444", 120),
    C("hold.split.capture", "holdout", "split", "split", "compiled", r"([;|])", "a;b|c;d|e;f|g;h", 160),
    C("hold.sub.template", "holdout", "sub", "sub", "compiled", r"(?P<left>[A-Z]+)_(?P<right>[0-9]+)", "AA_1 BB_22 CCC_333", 144, repl=r"\g<right>-\g<left>"),
    C("hold.subn.callable", "holdout", "subn-callable", "subn", "compiled", r"[A-Z]+", "ONE 1 TWO 2 THREE", 128, repl={"callable": "lower_bracket"}, count=2),
    C("hold.bytes.tokens", "holdout", "bytes", "findall", "compiled", rb"[0-9]+|[A-Za-z]+", b"ab12 cd345 \x80 EF7", 128),
    C("hold.unicode.words", "holdout", "unicode", "findall", "compiled", r"\d+|\w+", "café ٣٣ 雪_2 İı", 128),
    C("hold.cold.compile-search", "holdout", "cold", "search", "cold", r"(?P<tag>[A-Z]+)_[0-9]{1,3}", "prefix TAG_127 suffix", 40),
    C("hold.module.warm", "holdout", "module", "search", "module", r"[A-Z]+_[0-9]+", "prefix ITEM_730 suffix", 256),
    C("hold.empty.finditer", "holdout", "empty", "finditer", "compiled", r"(?=\s)|\B", "xy zt uv", 96),
    C("hold.backref.fullmatch", "holdout", "backref", "fullmatch", "compiled", r"([A-Z]{2,5}):\1", "ECHO:ECHO", 128),
    C("hold.conditional.match", "holdout", "conditional", "match", "compiled", r"(\[)?[0-9]+(?(1)\]|;)", "[2048] rest", 128),
    C("hold.atomic.search", "holdout", "branch-control", "search", "compiled", r"a*+b|cd+", "xx cdddd yy", 128),
    C("hold.byteslike.findall", "holdout", "bytes-like", "findall", "compiled", rb"[a-z]+|[0-9]+", b"ab12 cd345 ef7", 112, subject_kind="memoryview"),
    C("hold.unicode-name.search", "holdout", "unicode-name", "search", "compiled", r"\N{BLACK STAR}{2,4}", "begin ★★★ end", 128),
    C("hold.ignorecase.findall", "holdout", "ignore-case", "findall", "compiled", r"[a-z]+", "ONE Two THREE four", 128, flags=["I"]),
    C("hold.many.split", "holdout", "many-results", "split", "compiled", r"[|:]", "a|b:c|d:e|f:g|h:i|j:k|l", 112),
    C("hold.escape.bytes", "holdout", "escape", "escape", "module", b"A+B [x] # tag\\tail", None, 224),
    C("hold.compile.only", "holdout", "compile", "compile", "cold", r"(?P<tag>[A-Z]{2,8})(?:_[0-9]{1,3})+", None, 32),
    C("hold.scanner.search", "holdout", "scanner", "scanner", "compiled", r"(?P<word>[A-Z]+):[0-9]+", "A:1 BB:22 CCC:333 DDDD:4444", 96),
    C("hold.match.surface", "holdout", "match-surface", "match-surface", "compiled", r"(?P<left>[A-Z]+)_(?P<right>[0-9]+)", "prefix ITEM_730 suffix", 144, expand=r"\g<right>-\g<left>"),

    C("cal.real.log", "calibration", "real-log", "finditer", "compiled", r"(?P<method>GET|POST|PUT|DELETE) (?P<path>/[A-Za-z0-9_./-]+) HTTP/[0-9.]+", '10.0.0.1 "GET /api/v1/items HTTP/1.1" 200\n10.0.0.2 "POST /upload/a_2 HTTP/1.1" 201', 80),
    C("cal.real.url", "calibration", "real-url", "search", "compiled", r"(?P<scheme>https?)://(?P<host>[A-Za-z0-9.-]+)(?::(?P<port>[0-9]+))?(?P<path>/[^ ?#]*)?", "see https://example.org:8443/docs/a-b?q=1", 128),
    C("cal.real.email", "calibration", "real-email", "findall", "compiled", r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", "to:a.one@example.org cc:b+tag@sub.example.net", 112),
    C("cal.real.datetime", "calibration", "real-datetime", "search", "compiled", r"(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})[ T](?P<time>[0-9]{2}:[0-9]{2}:[0-9]{2})(?:\.[0-9]+)?Z?", "at 2026-07-21T23:14:08.127Z ready", 128),
    C("cal.real.version", "calibration", "real-version", "fullmatch", "compiled", r"v?[0-9]+\.[0-9]+\.[0-9]+(?:-(?:alpha|beta|rc)[0-9]*)?(?:\+[A-Za-z0-9.-]+)?", "v3.14.6-rc2+linux.x86_64", 96),
    C("cal.real.uuid", "calibration", "real-uuid", "search", "compiled", r"[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}", "request=4d3c2b1a-0123-4abc-8def-0123456789ab ok", 128),
    C("cal.real.ip", "calibration", "real-ip", "fullmatch", "compiled", r"(?:25[0-5]|2[0-4][0-9]|1?[0-9]{1,2})(?:\.(?:25[0-5]|2[0-4][0-9]|1?[0-9]{1,2})){3}", "192.168.42.7", 80),
    C("cal.real.path", "calibration", "real-path", "findall", "compiled", r"(?:^|\s)(?:\./|/)?[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)+", "open ./src/main.py then /var/log/service/error.log", 112),
    C("cal.real.config", "calibration", "real-config", "finditer", "compiled", r"^(?P<key>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?P<value>[^#\n]*?)\s*(?:#.*)?$", "PORT = 8080\nNAME=alpha beta # service\nDEBUG = false", 72, flags=["M"]),
    C("cal.real.comments", "calibration", "real-comments", "findall", "compiled", r"#[^\n]*$", "x = 1 # first\ny = 2\n# whole line\nz = 3 # last", 112, flags=["M"]),
    C("cal.real.whitespace", "calibration", "real-whitespace", "sub", "compiled", r"\s+", " alpha\t beta\n\n gamma   delta ", 128, repl=" "),
    C("cal.real.lines", "calibration", "real-lines", "sub", "compiled", r"^[ \t]+|[ \t]+$", "  first  \n\tsecond\t\n third   ", 112, repl="", flags=["M"]),
    C("cal.real.markup", "calibration", "real-markup", "findall", "compiled", r"<(?P<tag>[A-Za-z][A-Za-z0-9]*)\b[^>]*>", '<main id="x"><section><a href="/docs">docs</a></section></main>', 104),
    C("cal.real.quotes", "calibration", "real-quotes", "findall", "compiled", r"([\"'])(.*?)\1", 'title="alpha beta" name=\'gamma\' plain=delta', 88),
    C("cal.real.csv", "calibration", "real-csv", "split", "compiled", r',(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)', 'one,"two,too",three,"four,4",five', 56),
    C("cal.branch.prefix", "calibration", "branch-prefix", "match", "compiled", r"(?:accept|access|account|action|active|actor|actual|adapt|address|admin)[A-Za-z0-9_-]*", "account_settings next", 112),
    C("cal.branch.miss", "calibration", "branch-miss", "search", "compiled", r"(?:amber|bronze|cobalt|denim|emerald|fuchsia|golden|hazel|indigo|jade)-[0-9]{2}", "ordinary words with no color and no code", 112),
    C("cal.repeat.nested", "calibration", "repeat-nested", "fullmatch", "compiled", r"(?:[A-Za-z]+(?:_[0-9]+)?)(?:/(?:[A-Za-z]+(?:_[0-9]+)?))*", "alpha_1/beta/gamma_22/delta", 96),
    C("cal.lines.records", "calibration", "lines-records", "finditer", "compiled", r"^(?:INFO|WARN|ERROR)\s+(?P<code>[A-Z]{2}[0-9]{3})\s+(?P<text>.+)$", "INFO AB123 started\nWARN ZX204 slow request\nERROR QQ500 failed", 80, flags=["M"]),
    C("cal.block.dotall", "calibration", "block-dotall", "search", "compiled", r"BEGIN\n(?P<body>.*?)\nEND", "prefix\nBEGIN\nline one\nline two\nEND\nsuffix", 104, flags=["S"]),
    C("cal.pattern.verbose", "calibration", "pattern-verbose", "search", "compiled", r"(?P<name>[A-Za-z_][A-Za-z0-9_]*) \s* = \s* (?P<num>[0-9]+) # assignment", "skip total_count = 4096 end", 104, flags=["X"]),
    C("cal.mode.ascii", "calibration", "mode-ascii", "findall", "compiled", r"\b\w+\b", "cafe café 雪 snow_2", 104, flags=["A"]),
    C("cal.mode.casefold", "calibration", "mode-casefold", "findall", "compiled", r"[a-z]+", "İıſK Kelvin Straße ALPHA", 88, flags=["I"]),
    C("cal.mode.astral", "calibration", "mode-astral", "findall", "compiled", r"[😀-🙏]+|\w+", "hello 😀😁😂 snow雪 🙏 end", 88),
    C("cal.look.negative-ahead", "calibration", "look-negative-ahead", "findall", "compiled", r"\b(?!tmp_)[A-Za-z_][A-Za-z0-9_]*\b", "tmp_one alpha tmp_two beta_2 gamma", 88),
    C("cal.look.negative-behind", "calibration", "look-negative-behind", "findall", "compiled", r"(?<![A-Za-z0-9_])#[A-Za-z][A-Za-z0-9_]*", "#one x#skip #two_2 end", 96),
    C("cal.bytes.replace", "calibration", "bytes-replace", "sub", "compiled", rb"([A-Z]+)=([0-9]+)", b"AA=1 BB=22 CC=333", 112, repl=rb"\2:\1"),
    C("cal.bytes.scan", "calibration", "bytes-scan", "scanner", "compiled", rb"(?P<key>[A-Za-z]+):(?P<num>[0-9]+)", b"a:1 bb:22 ccc:333 dddd:4444", 72),
    C("cal.compile.complex", "calibration", "compile-complex", "compile", "cold", r"^(?P<scheme>https?)://(?P<host>[A-Za-z0-9.-]+)(?::(?P<port>[0-9]{1,5}))?(?P<path>/[^?#]*)?(?:\?(?P<query>[^#]*))?$", None, 24),
    C("cal.module.replace", "calibration", "module-replace", "sub", "module", r"(?P<key>[a-z]+)=(?P<num>[0-9]+)", "a=1 bb=22 ccc=333", 112, repl=r"\g<num>/\g<key>"),
    C("cal.zero.boundary", "calibration", "zero-boundary", "finditer", "compiled", r"(?=,)|\b", "alpha,beta gamma,delta", 72),
    C("cal.dense.iter", "calibration", "dense-iter", "finditer", "compiled", r"[A-Za-z]+|[0-9]+|[^A-Za-z0-9\s]", "sum(a_2,17)+value-42/next;", 72),
    C("cal.capture.optional", "calibration", "capture-optional", "findall", "compiled", r"([A-Za-z]+)(?:=([0-9]+))?", "one=1 two three=333 four", 96),
    C("cal.split.limited", "calibration", "split-limited", "split", "compiled", r"\s*[,;|]\s*", "a, b; c | d, e; f | g", 104, maxsplit=4),
    C("cal.replace.limited", "calibration", "replace-limited", "subn", "compiled", r"[A-Za-z]+", "one 1 two 2 three 3 four 4", 104, repl="X", count=3),
    C("cal.bytes.view-long", "calibration", "bytes-view-long", "findall", "compiled", rb"[A-Z]{2}[0-9]{2}", (b"AA12 xx BB34 yy CC56 zz " * 12), 48, subject_kind="memoryview"),
    C("cal.window.search", "calibration", "window-search", "search", "compiled", r"[A-Z]{2}[0-9]+", "SKIP00 xx AB123 yy CD456 tail", 128, pos=7, endpos=24),
    C("cal.window.findall", "calibration", "window-findall", "findall", "compiled", r"[a-z]+", "skip alpha beta end gamma", 112, pos=5, endpos=20),
    C("cal.window.scanner", "calibration", "window-scanner", "scanner", "compiled", r"[A-Z]+:[0-9]+", "SKIP:0 A:1 BB:22 CC:333 TAIL:9", 72, pos=7, endpos=25),
    C("cal.window.match", "calibration", "window-match", "match", "compiled", r"[A-Z]{2}[0-9]{2}", "prefix AB42 suffix", 128, pos=7, endpos=11),
    C("cal.literal.replace", "calibration", "literal-replace", "sub", "compiled", r"ERROR", "INFO ok ERROR one WARN slow ERROR two", 144, repl="E"),
    C("cal.template.repeat", "calibration", "template-repeat", "sub", "compiled", r"(?P<word>[a-z]+)", "alpha beta gamma delta", 112, repl=r"<\g<word>|\g<word>>"),
    C("cal.match.miss", "calibration", "match-miss", "match", "compiled", r"(?:GET|POST|PUT) /[A-Za-z0-9/_-]+", "ordinary text without a request", 160),
    C("cal.fullmatch.miss", "calibration", "fullmatch-miss", "fullmatch", "compiled", r"[A-Z]{2}(?:-[0-9]{3}){2,4}", "AB-123-45x", 144),

    C("hold.real.log", "holdout", "real-log", "finditer", "compiled", r"(?P<method>GET|POST|PATCH|DELETE) (?P<path>/[A-Za-z0-9_./-]+) HTTP/[0-9.]+", '172.0.0.1 "PATCH /v2/users/me HTTP/2.0" 204\n172.0.0.2 "GET /assets/app_4.js HTTP/1.1" 200', 80),
    C("hold.real.url", "holdout", "real-url", "search", "compiled", r"(?P<scheme>https?|ftp)://(?P<host>[A-Za-z0-9.-]+)(?::(?P<port>[0-9]+))?(?P<path>/[^ ?#]*)?", "link ftp://files.example.net:2121/releases/v4.2.tar?q=no", 128),
    C("hold.real.email", "holdout", "real-email", "findall", "compiled", r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", "owner=x_2@demo.io; reply=help+us@mail.example.co", 112),
    C("hold.real.datetime", "holdout", "real-datetime", "search", "compiled", r"(?P<date>[0-9]{4}/[0-9]{2}/[0-9]{2})[ T](?P<time>[0-9]{2}:[0-9]{2}:[0-9]{2})(?:\.[0-9]+)?(?:Z|[+-][0-9]{2}:[0-9]{2})?", "done 2026/08/14 06:31:02+01:00 status=ok", 128),
    C("hold.real.version", "holdout", "real-version", "fullmatch", "compiled", r"v?[0-9]+\.[0-9]+(?:\.[0-9]+)?(?:-(?:dev|pre|rc)[0-9]*)?(?:\+[A-Za-z0-9.-]+)?", "12.4.9-pre7+mac.arm64", 96),
    C("hold.real.uuid", "holdout", "real-uuid", "search", "compiled", r"[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}", "trace=ABCDEF12-3456-4ABC-9DEF-0123456789AB end", 128),
    C("hold.real.ip", "holdout", "real-ip", "fullmatch", "compiled", r"(?:25[0-5]|2[0-4][0-9]|1?[0-9]{1,2})(?:\.(?:25[0-5]|2[0-4][0-9]|1?[0-9]{1,2})){3}", "10.204.0.255", 80),
    C("hold.real.path", "holdout", "real-path", "findall", "compiled", r"(?:^|\s)(?:\.\./|/)?[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)+", "read ../tests/data/input.json and /opt/app/bin/run-task", 112),
    C("hold.real.config", "holdout", "real-config", "finditer", "compiled", r"^(?P<key>[A-Za-z_][A-Za-z0-9_]*)\s*:\s*(?P<value>[^#\n]*?)\s*(?:#.*)?$", "host: api.local\nmax_items : 250 # cap\nenabled: true", 72, flags=["M"]),
    C("hold.real.comments", "holdout", "real-comments", "findall", "compiled", r"//[^\n]*$", "let x = 1; // first\nlet y = 2;\n// whole\nreturn y; // end", 112, flags=["M"]),
    C("hold.real.whitespace", "holdout", "real-whitespace", "sub", "compiled", r"\s+", "\tone  two\nthree\r\nfour   five ", 128, repl=" "),
    C("hold.real.lines", "holdout", "real-lines", "sub", "compiled", r"^[ \t]+|[ \t]+$", "\talpha  \n beta\t\n  gamma   ", 112, repl="", flags=["M"]),
    C("hold.real.markup", "holdout", "real-markup", "findall", "compiled", r"<(?P<tag>[A-Za-z][A-Za-z0-9]*)\b[^>]*>", '<article><h2 class="lead">Hi</h2><img src="/a.png"/><p>text</p></article>', 104),
    C("hold.real.quotes", "holdout", "real-quotes", "findall", "compiled", r"([\"'])(.*?)\1", 'first=\'one two\' second="three" bare=four', 88),
    C("hold.real.csv", "holdout", "real-csv", "split", "compiled", r',(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)', 'red,"blue,green",yellow,"black,white",violet', 56),
    C("hold.branch.prefix", "holdout", "branch-prefix", "match", "compiled", r"(?:build|bundle|button|buffer|bucket|budget|binary|bitmap|border|bottom)[A-Za-z0-9_-]*", "buffer_size trailing", 112),
    C("hold.branch.miss", "holdout", "branch-miss", "search", "compiled", r"(?:cedar|birch|maple|willow|spruce|poplar|walnut|aspen|cherry|olive)_[0-9]{2}", "regular prose without tree names or identifiers", 112),
    C("hold.repeat.nested", "holdout", "repeat-nested", "fullmatch", "compiled", r"(?:[A-Z]+(?:-[0-9]+)?)(?:\.(?:[A-Z]+(?:-[0-9]+)?))*", "ALPHA-1.BETA.GAMMA-22.DELTA", 96),
    C("hold.lines.records", "holdout", "lines-records", "finditer", "compiled", r"^(?:TRACE|DEBUG|FATAL)\s+(?P<code>[A-Z]{3}[0-9]{2})\s+(?P<text>.+)$", "TRACE NET01 connected\nDEBUG CFG20 loaded\nFATAL APP99 stopped", 80, flags=["M"]),
    C("hold.block.dotall", "holdout", "block-dotall", "search", "compiled", r"START\n(?P<body>.*?)\nSTOP", "header\nSTART\nfirst row\nsecond row\nSTOP\nfooter", 104, flags=["S"]),
    C("hold.pattern.verbose", "holdout", "pattern-verbose", "search", "compiled", r"(?P<name>[A-Za-z_][A-Za-z0-9_]*) \s* : \s* (?P<num>[0-9]+) # field", "prefix item_total : 730 suffix", 104, flags=["X"]),
    C("hold.mode.ascii", "holdout", "mode-ascii", "findall", "compiled", r"\b\w+\b", "naive naïve café 雪 item_7", 104, flags=["A"]),
    C("hold.mode.casefold", "holdout", "mode-casefold", "findall", "compiled", r"[a-z]+", "ſİıK KELVIN alpha CAFÉ", 88, flags=["I"]),
    C("hold.mode.astral", "holdout", "mode-astral", "findall", "compiled", r"[😀-🙏]+|\w+", "start 🙃🙂 snow雪 😀 end_2", 88),
    C("hold.look.negative-ahead", "holdout", "look-negative-ahead", "findall", "compiled", r"\b(?!skip_)[A-Za-z_][A-Za-z0-9_]*\b", "skip_one ready skip_two item_3 final", 88),
    C("hold.look.negative-behind", "holdout", "look-negative-behind", "findall", "compiled", r"(?<![A-Za-z0-9_])@[A-Za-z][A-Za-z0-9_]*", "@one x@skip @two_2 end", 96),
    C("hold.bytes.replace", "holdout", "bytes-replace", "sub", "compiled", rb"([a-z]+):([0-9]+)", b"a:1 bb:22 ccc:333", 112, repl=rb"\2=\1"),
    C("hold.bytes.scan", "holdout", "bytes-scan", "scanner", "compiled", rb"(?P<key>[A-Z]+)=(?P<num>[0-9]+)", b"A=1 BB=22 CCC=333 DDDD=4444", 72),
    C("hold.compile.complex", "holdout", "compile-complex", "compile", "cold", r"^(?P<user>[A-Za-z0-9._+-]+)@(?P<host>[A-Za-z0-9.-]+)(?::(?P<port>[0-9]{1,5}))?(?P<path>/[A-Za-z0-9_./-]*)?(?:\?(?P<query>[^#]*))?$", None, 24),
    C("hold.module.replace", "holdout", "module-replace", "sub", "module", r"(?P<key>[A-Z]+):(?P<num>[0-9]+)", "A:1 BB:22 CCC:333", 112, repl=r"\g<num>_\g<key>"),
    C("hold.zero.boundary", "holdout", "zero-boundary", "finditer", "compiled", r"(?=;)|\b", "one;two three;four", 72),
    C("hold.dense.iter", "holdout", "dense-iter", "finditer", "compiled", r"[A-Za-z]+|[0-9]+|[^A-Za-z0-9\s]", "call(x_3,29)-other+17*next!", 72),
    C("hold.capture.optional", "holdout", "capture-optional", "findall", "compiled", r"([A-Z]+)(?:=([0-9]+))?", "ONE=1 TWO THREE=333 FOUR", 96),
    C("hold.split.limited", "holdout", "split-limited", "split", "compiled", r"\s*[:|/]\s*", "a: b | c / d: e | f / g", 104, maxsplit=4),
    C("hold.replace.limited", "holdout", "replace-limited", "subn", "compiled", r"[A-Z]+", "ONE 1 TWO 2 THREE 3 FOUR 4", 104, repl="x", count=3),
    C("hold.bytes.view-long", "holdout", "bytes-view-long", "findall", "compiled", rb"[a-z]{2}[0-9]{2}", (b"ab12 XX cd34 YY ef56 ZZ " * 12), 48, subject_kind="memoryview"),
    C("hold.window.search", "holdout", "window-search", "search", "compiled", r"[A-Z]{3}[0-9]+", "SKIP000 xx TAG127 yy END730 tail", 128, pos=8, endpos=25),
    C("hold.window.findall", "holdout", "window-findall", "findall", "compiled", r"[A-Z]+", "SKIP ONE TWO END THREE", 112, pos=5, endpos=16),
    C("hold.window.scanner", "holdout", "window-scanner", "scanner", "compiled", r"[a-z]+=[0-9]+", "skip=0 a=1 bb=22 cc=333 tail=9", 72, pos=7, endpos=25),
    C("hold.window.match", "holdout", "window-match", "match", "compiled", r"[A-Z]{3}[0-9]{2}", "prefix TAG42 suffix", 128, pos=7, endpos=12),
    C("hold.literal.replace", "holdout", "literal-replace", "sub", "compiled", r"WARN", "INFO ok WARN one ERROR bad WARN two", 144, repl="W"),
    C("hold.template.repeat", "holdout", "template-repeat", "sub", "compiled", r"(?P<word>[A-Z]+)", "ONE TWO THREE FOUR", 112, repl=r"[\g<word>|\g<word>]"),
    C("hold.match.miss", "holdout", "match-miss", "match", "compiled", r"(?:TRACE|DEBUG|FATAL) [A-Z]{3}[0-9]{2}", "ordinary text without a log prefix", 160),
    C("hold.fullmatch.miss", "holdout", "fullmatch-miss", "fullmatch", "compiled", r"[A-Z]{3}(?:_[0-9]{2}){2,4}", "TAG_12_3x", 144),
]


def cases():
    return list(CASES)
