#!/usr/bin/env python3
"""Generate and prove the larger, isolated Rust Unicode-table alternative.

Reuse the frozen production table generator and complete independent scalar
verifier. Never replace or edit the selected production Unicode module.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import importlib.util
import json
import pathlib
import subprocess
import sys


sys.dont_write_bytecode = True


def load_sibling(name: str) -> object:
    path = pathlib.Path(__file__).resolve().with_name(f"{name}.py")
    specification = importlib.util.spec_from_file_location(name, path)
    if specification is None or specification.loader is None:
        raise RuntimeError(f"cannot load independent Unicode tool: {path}")
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


production_verify = load_sibling("rust_unicode_production_verify")
table_lab = load_sibling("rust_unicode_table_lab")


BMP_SOURCE_SHA256 = (
    "ea93d9bfd3d089a9333a38e3eabdaf05ae932a6b01b3a6fe8f388808ae47107d"
)
BMP_PROPERTY_PREFIX = 65_536
PRODUCTION_PROPERTY_PREFIX = 16_384
ADDED_PROPERTY_BYTES = BMP_PROPERTY_PREFIX - PRODUCTION_PROPERTY_PREFIX


def production_mask(value: int) -> int:
    """Convert frozen generator bits into the existing matcher contract."""

    return (
        ((value & 0x02) >> 1)
        | ((value & 0x20) >> 4)
        | ((value & 0x01) << 2)
        | ((value & 0x04) << 1)
        | ((value & 0x08) << 1)
        | ((value & 0x10) << 1)
        | (value & 0xC0)
    )


def bmp_production_source(**arguments: object) -> str:
    """Change only the exactly measured first-65,536-character prefix."""

    index = arguments["property_index"]
    pages = arguments["property_pages"]
    if not isinstance(index, list) or not isinstance(pages, list):
        raise RuntimeError("invalid frozen production property pages")
    mapped = [production_mask(value) for value in pages]
    original_prefix = [
        mapped[(index[value >> 8] << 8) + (value & 0xFF)]
        for value in range(PRODUCTION_PROPERTY_PREFIX)
    ]
    larger_prefix = [
        mapped[(index[value >> 8] << 8) + (value & 0xFF)]
        for value in range(BMP_PROPERTY_PREFIX)
    ]
    original_array = table_lab.production_array(
        "PROPERTY_PREFIX_16K", "u8", original_prefix
    )
    larger_array = table_lab.production_array(
        "PROPERTY_PREFIX_BMP", "u8", larger_prefix
    )
    source = ORIGINAL_PRODUCTION_SOURCE(**arguments)
    if source.count(original_array) != 1:
        raise RuntimeError("the exact frozen 16K production array changed")
    source = source.replace(original_array, larger_array, 1)

    original_lookup = (
        "    if value < 0x4000 {\n"
        "        return PROPERTY_PREFIX_16K[value as usize];\n"
        "    }"
    )
    larger_lookup = (
        "    if value < 0x1_0000 {\n"
        "        return PROPERTY_PREFIX_BMP[value as usize];\n"
        "    }"
    )
    if source.count(original_lookup) != 1:
        raise RuntimeError("the frozen production property lookup changed")
    source = source.replace(original_lookup, larger_lookup, 1)

    original_header = (
        "// Generated by tools/rust_unicode_table_lab.py; do not hand-edit.\n"
    )
    larger_header = (
        "// Generated by tools/rust_unicode_bmp_production_generate.py; "
        "do not hand-edit.\n"
    )
    if not source.startswith(original_header):
        raise RuntimeError("the frozen production generator header changed")
    source = larger_header + source[len(original_header) :]

    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    if digest != BMP_SOURCE_SHA256:
        raise RuntimeError(
            "the frozen full-API basic-plane alternative changed: "
            f"expected {BMP_SOURCE_SHA256}, observed {digest}"
        )
    return source


ORIGINAL_PRODUCTION_SOURCE = table_lab.production_source


def assert_production_unchanged(path: pathlib.Path, expected: str) -> None:
    observed = production_verify.sha256(path)
    if observed != expected:
        raise RuntimeError(
            "the selected production Unicode source must remain unchanged: "
            f"expected {expected}, observed {observed}"
        )


def check_rust_format(path: pathlib.Path) -> None:
    checked = subprocess.run(
        ["rustfmt", "--check", "--edition", "2024", str(path)],
        text=True,
        capture_output=True,
        check=False,
    )
    if checked.returncode:
        raise RuntimeError(
            "the isolated basic-plane Unicode source fails rustfmt: "
            f"{checked.stdout}{checked.stderr}"
        )


def scalar_evidence(workspace: pathlib.Path) -> dict[str, object]:
    path = (
        workspace / "candidates" / "evidence" / "rust-v6-unicode-table-lab.json.gz"
    )
    compressed = path.read_bytes()
    evidence = json.loads(gzip.decompress(compressed))
    if evidence["production_module"]["sha256"] != production_verify.SOURCE_SHA256:
        raise RuntimeError("the final frozen Unicode lab baseline changed")
    if evidence["generator_sha256"] != production_verify.sha256(
        workspace / "tools" / "rust_unicode_table_lab.py"
    ):
        raise RuntimeError("the final frozen Unicode lab generator changed")
    baseline_name = "mixed-prefix-property16k-fold4k"
    alternative_name = "mixed-prefix-propertybmp-fold4k"
    overall = {row["implementation"]: row for row in evidence["overall"]}
    if alternative_name not in overall or baseline_name not in overall:
        raise RuntimeError("the frozen Unicode archive omitted an alternative")
    added = (
        evidence["binary"][alternative_name]["added_bytes"]
        - evidence["binary"][baseline_name]["added_bytes"]
    )
    if added != ADDED_PROPERTY_BYTES:
        raise RuntimeError("the measured basic-plane property size changed")
    return {
        "path": "candidates/evidence/rust-v6-unicode-table-lab.json.gz",
        "sha256": hashlib.sha256(compressed).hexdigest(),
        "implementations": len(evidence["implementations"]),
        "raw_rows": len(evidence["raw"]),
        "full_plane_comparisons": evidence["full_plane_comparisons"],
        "baseline_implementation": baseline_name,
        "baseline_scalar_speedup": overall[baseline_name]["speedup_geomean"],
        "alternative_implementation": alternative_name,
        "alternative_scalar_speedup": overall[alternative_name][
            "speedup_geomean"
        ],
        "additional_property_bytes": added,
        "end_to_end_performance": "NOT MEASURED",
    }


def verify_alternative(source: pathlib.Path, output: pathlib.Path) -> int:
    previous_arguments = sys.argv
    previous_expected = production_verify.SOURCE_SHA256
    try:
        production_verify.SOURCE_SHA256 = BMP_SOURCE_SHA256
        sys.argv = [
            str(pathlib.Path(production_verify.__file__).resolve()),
            "--source",
            str(source),
            "--output",
            str(output),
        ]
        return production_verify.main()
    finally:
        sys.argv = previous_arguments
        production_verify.SOURCE_SHA256 = previous_expected


def main() -> int:
    workspace = pathlib.Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--module",
        type=pathlib.Path,
        default=pathlib.Path("/tmp/rebar-rust-unicode-bmp-production.rs"),
    )
    parser.add_argument(
        "--lab-source",
        type=pathlib.Path,
        default=pathlib.Path("/tmp/rebar-rust-unicode-bmp-project-lab.rs"),
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=(
            workspace
            / "candidates"
            / "evidence"
            / "rust-v6-unicode-bmp-production-fullplane.json"
        ),
    )
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="generate and format-check the isolated alternative without verifying",
    )
    args = parser.parse_args()
    stable = (
        workspace / "candidates" / "rust" / "src" / "unicode_tables.rs"
    ).resolve()
    stable_digest = production_verify.SOURCE_SHA256
    module = args.module.resolve()
    lab_source = args.lab_source.resolve()
    output = args.output.resolve()
    approved_evidence = (
        workspace
        / "candidates"
        / "evidence"
        / "rust-v6-unicode-bmp-production-fullplane.json"
    ).resolve()
    if output in {stable, module, lab_source}:
        raise RuntimeError(
            "the proof output must not overwrite production or generated sources"
        )
    if output.is_relative_to(workspace) and output != approved_evidence:
        raise RuntimeError(
            "in-workspace proof output must use the approved alternative evidence"
        )
    if module.is_relative_to(workspace) or lab_source.is_relative_to(workspace):
        raise RuntimeError("the alternative and its build source must be isolated")
    if module == lab_source:
        raise RuntimeError("the isolated build and production source must differ")
    assert_production_unchanged(stable, stable_digest)
    table_lab.validate_frozen_fixture(workspace)

    try:
        table_lab.production_source = bmp_production_source
        tables = table_lab.generate(lab_source, module)
    finally:
        table_lab.production_source = ORIGINAL_PRODUCTION_SOURCE
    generated = tables["production"]
    if generated is None or generated["source_sha256"] != BMP_SOURCE_SHA256:
        raise RuntimeError("the complete basic-plane source is not reproducible")
    generated["property_prefix_bytes"] = BMP_PROPERTY_PREFIX
    check_rust_format(module)
    assert_production_unchanged(stable, stable_digest)

    if args.generate_only:
        print(
            json.dumps(
                {
                    "schema": "rebar-rust-unicode-bmp-generation-v1",
                    "source_sha256": BMP_SOURCE_SHA256,
                    "property_prefix_bytes": BMP_PROPERTY_PREFIX,
                    "additional_property_bytes": ADDED_PROPERTY_BYTES,
                    "production_source_sha256": stable_digest,
                    "production_unchanged": True,
                    "end_to_end_performance": "NOT MEASURED",
                    "module": str(module),
                },
                sort_keys=True,
            )
        )
        return 0

    result = verify_alternative(module, output)
    assert_production_unchanged(stable, stable_digest)
    proof = json.loads(output.read_text(encoding="utf-8"))
    proof["alternative"] = {
        "generator": "tools/rust_unicode_bmp_production_generate.py",
        "generator_sha256": production_verify.sha256(pathlib.Path(__file__)),
        "base_generator_sha256": production_verify.sha256(
            workspace / "tools" / "rust_unicode_table_lab.py"
        ),
        "selected_production_sha256": stable_digest,
        "selected_production_unchanged": True,
        "property_prefix_bytes": BMP_PROPERTY_PREFIX,
        "selected_property_prefix_bytes": PRODUCTION_PROPERTY_PREFIX,
        "additional_property_bytes": ADDED_PROPERTY_BYTES,
        "scalar_lab": scalar_evidence(workspace),
        "end_to_end_performance": "NOT MEASURED",
    }
    output.write_text(
        json.dumps(proof, ensure_ascii=True, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )
    if result or proof["failures"]:
        return 1
    print(
        json.dumps(
            {
                "output": str(output),
                "source_sha256": BMP_SOURCE_SHA256,
                "production_source_sha256": stable_digest,
                "production_unchanged": True,
                "full_plane_comparisons": proof["full_plane_comparisons"],
                "total_mismatches": proof["total_mismatches"],
                "additional_property_bytes": ADDED_PROPERTY_BYTES,
                "end_to_end_performance": "NOT MEASURED",
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
